version: "3"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_HOST=${TYPEORM_HOST}
      - POSTGRESQL_USERNAME=${TYPEORM_USERNAME}
      - POSTGRESQL_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRESQL_DATABASE=${TYPEORM_DATABASE}
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
